//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatisiertes_Kopieren.Translations {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automatisiertes_Kopieren.Translations.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of birth could not be extracted. ähnelt.
        /// </summary>
        internal static string BirthDateExtractionError {
            get {
                return ResourceManager.GetString("BirthDateExtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files copied and renamed successfully. ähnelt.
        /// </summary>
        internal static string CopyRenamedSuccessfully {
            get {
                return ResourceManager.GetString("CopyRenamedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error extracting protocol number. ähnelt.
        /// </summary>
        internal static string ErrorExtractProtocolNumber {
            get {
                return ResourceManager.GetString("ErrorExtractProtocolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Child&apos;s age could not be extracted from Excel. ähnelt.
        /// </summary>
        internal static string ExcelCantExtractAge {
            get {
                return ResourceManager.GetString("ExcelCantExtractAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error extracting months from Excel. ähnelt.
        /// </summary>
        internal static string ExcelCantExtractMonths {
            get {
                return ResourceManager.GetString("ExcelCantExtractMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The required Excel document could not be found. Please check the path and try again. ähnelt.
        /// </summary>
        internal static string ExcelNotFoundCheckPath {
            get {
                return ResourceManager.GetString("ExcelNotFoundCheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file manager is not initialized. ähnelt.
        /// </summary>
        internal static string FileManagerNotInitialized {
            get {
                return ResourceManager.GetString("FileManagerNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please fill out all required fields. ähnelt.
        /// </summary>
        internal static string FillOutRequiredFields {
            get {
                return ResourceManager.GetString("FillOutRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid name. Please check the data. ähnelt.
        /// </summary>
        internal static string InvalidKidName {
            get {
                return ResourceManager.GetString("InvalidKidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the main directory. ähnelt.
        /// </summary>
        internal static string SelectHomeFolderText {
            get {
                return ResourceManager.GetString("SelectHomeFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a kid name before updating the worksheet. ähnelt.
        /// </summary>
        internal static string SelectKidNameBeforeUpdateWorksheet {
            get {
                return ResourceManager.GetString("SelectKidNameBeforeUpdateWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide a valid year for the report. ähnelt.
        /// </summary>
        internal static string SelectValidYear {
            get {
                return ResourceManager.GetString("SelectValidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred while processing the Excel file: {0} ähnelt.
        /// </summary>
        internal static string UnexpectedExcelError {
            get {
                return ResourceManager.GetString("UnexpectedExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide a valid first and last name. ähnelt.
        /// </summary>
        internal static string ValidFirstAndLastName {
            get {
                return ResourceManager.GetString("ValidFirstAndLastName", resourceCulture);
            }
        }
    }
}
